name: Deploy Resume

on:
  push:
    branches:
      - feature/upgrade
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Setup builder
        run: yarn install --frozen-lockfile

      - name: Build Pages
        run: |
          mkdir public
          npx resumed render index.json -o public/index.html

      - name: Build PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./public/index.html
          outputFile: ./public/resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: false
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: "Deployment ${{ steps.prepare_tag.outputs.tag_name }}"
